apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listing-api
  template:
    metadata:
      labels:
        app: listing-api
    spec:
      containers:
      - name: listing-api
        image: docker.io/saki709/pulito-listing-api:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-postgresql
              key: postgres-password
        - name: RABBIT_PASS
          valueFrom:
            secretKeyRef:
              name: rmq-rabbitmq
              key: rabbitmq-password
        - name: ENV
          value: dev
        - name: DB_URI
          value: "postgresql://postgres:$(DB_PASS)@db-postgresql.default.svc.cluster.local/postgres"
        - name: RABBIT_URI
          value: "amqp://user:$(RABBIT_PASS)@rmq-rabbitmq.default.svc.cluster.local"
      
---
apiVersion: v1
kind: Service
metadata:
  name: listing-service
spec:
  selector:
    app: listing-api
  ports:
  - name: http
    port: 8080
    targetPort: 5000
